# Generated by Django 4.0.6 on 2022-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-date_joined',)},
        ),
    ]
