# Generated by Django 3.2.9 on 2022-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='media/avis/', verbose_name='Profile Picture'),
        ),
    ]
