# Generated by Django 3.2.9 on 2022-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20220621_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='testing-the-new-db', unique=True),
            preserve_default=False,
        ),
    ]
