# Generated by Django 3.2.9 on 2022-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20220702_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='media/avis/', verbose_name='Profile Picture'),
        ),
    ]
