# Generated by Django 4.0.6 on 2022-07-09 17:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
