# Generated by Django 3.2.9 on 2022-03-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_rename_user_blogpost_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="User",
            new_name="owner",
        ),
    ]
