# Generated by Django 3.2.9 on 2022-03-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_rename_user_blogpost_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["date_added"]},
        ),
    ]
