# Generated by Django 3.2.9 on 2022-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_auto_20220416_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
