# Generated by Django 3.2.9 on 2022-04-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_author_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(null=True),
        ),
    ]
