# Generated by Django 3.2.9 on 2022-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0015_author_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="text",
            field=models.TextField(),
        ),
    ]
