# Generated by Django 3.2.9 on 2022-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_alter_blogpost_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
