# Generated by Django 3.2.9 on 2022-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
