# Generated by Django 3.2.9 on 2022-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0018_blogpost_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield", max_length=100, null=True
            ),
        ),
    ]
